services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik-docker-stack_traefik_network
    restart: always
    ports:
      - "5432:5432"
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.web.entrypoints=websecure
      - traefik.http.routers.web.tls.certresolver=${CERTRESOLVER}
      - io.portainer.accesscontrol.public=true

networks:
  traefik-docker-stack_traefik_network:
    external: true

volumes:
  postgres_data:
    driver: local
